### ISSUE TITLE
LF instead of CR+LF

### ISSUE THREAD

**Issue by cedricbonhomme** [rodekruis/shelter-database#1]
Hello @humanitariandata ,

Is there a reason to switch to CR+LF formating?
I think that it would be good to switch back to LF for all files, as @mjvanderveen  did ( 128d0df ) .
It will be easier for me to follow the project.
If needed I can send a PR.

thanks,

Cédric

**Comment by mjvanderveen** [comment]
Hi @cedricbonhomme,

Yes, I perform this command on init_db.sh because otherwise it is formatted for windows and fails on unix/ubuntu with a /bin/sh^M error.

Are you running on windows?

**Comment by cedricbonhomme** [comment]
I am using Debian, no Windows fo me.

I experienced the same problem when I wanted to run drop_db.sh. Then I realized that almost all files were in CR+LF mode. So I pushed a commit just to switch back to LF.

**Comment by mjvanderveen** [comment]
What command do you use? then I will execute it on the whole repository.

**Comment by cedricbonhomme** [comment]
This command should do the trick: `find . -type f -not -path ".git*"  -print0 | xargs -0 dos2unix`

**Comment by cedricbonhomme** [comment]
Maybe someone is using a very old Windows and/or have `autocrlf` to true in the Git config.

**Comment by mjvanderveen** [comment]
@ar-ge @Krysia can you check your settings?

**Comment by Krysia** [comment]
Hi, I'm using mac, I checked conf.cfg file,  autocrlf setting is not listed.

**Comment by cedricbonhomme** [comment]
I suspect that this c5aeb31 added all the CR.

**Comment by arongergely** [comment]
@mjvanderveen I also just checked git config,  don't have autocrlf. maybe something happened on your side?
