### ISSUE TITLE
Issues_drawings

### ISSUE THREAD

**Issue by shaktirajshrestha** [rodekruis/shelter-database#11]
First, one of the main issues is regarding absence of proper dimensions in the drawings. Also, there are no detailed construction drawings such as section drawings. So to actually implement these drawings in a site is quite challenging. 

Second, I tried to add a new shelter and after the 7 steps are completed I tried to upload some drawings in the structure tab. But it already shows me drawings from another shelter rather than an option to add the data. Furthermore, I am not sure what type of files are permitted to add in this. It would be great if more file formats such as autocad, sketchup, revit etc. could be added so that people can download them and make alterations to them as they need it.

**Comment by mjvanderveen** [comment]
Drawings are precreated by the SRU en these are just supportive to correctly understand the different data requested.

I've allowed upload of autocad and sketchup. Revit is an octet-stream and this is a dangerous mime type.
