### ISSUE TITLE
issue_zoom and search

### ISSUE THREAD

**Issue by shaktirajshrestha** [rodekruis/shelter-database#13]
When I zoom into the maps, say, in Kathmandu, Nepal to look for shelter it shows me some locations. But at that moment if i try to change the location and type it in the search bar, say Bangladesh, it does not take me to the new location automatically. Even after refreshing the page, I am still in the older map. I can only look for a new location after I go to Shelter tab again, and do the search from the beginning. So an automatic location after some one types a new location would be really easy to use.

**Comment by mjvanderveen** [comment]
This has been fixed
