### ISSUE TITLE
Add shelter

### ISSUE THREAD

**Issue by Jonath510** [rodekruis/shelter-database#18]
On the page where you can add a shelter, at "why add your shelter", it says "Deel kennis" in Dutch. Probably better to translate that to share knowledge?
When starting the process, the information fields are in Dutch (unlike in the instruction video) and I cannot upload the implementing organization and therefore get stuck at step 2.

**Comment by mjvanderveen** [comment]
Translation process will be separately handled by transifex. Still to be done.

There seems to be an issue with the humanitarianresponse.info api (irregular) where there is no network request by the shelter-database to retrieve the organizations. This is handled in contribute.js.

**Comment by mjvanderveen** [comment]
Maybe this last point also has to do with the http vs https.

**Comment by mjvanderveen** [comment]
The problem still persist. The lookup to humanitarianresponse.info organizations api returns a 'results could not be loaded' error. This doesn't happen on localhost and dev environment, only on shelter-database.org. @thenav56 could you see if you can identify the problem?
