### ISSUE TITLE
Zoom

### ISSUE THREAD

**Issue by SvetlanaKalyagina** [rodekruis/shelter-database#21]
When I try to zoom out, I get the map with previous zoom, it jumps back.

**Comment by mjvanderveen** [comment]
This has to do with a looping behavior of the mapFilter in src/web/static/js/dashboard.js: onMapFiltered.

I've made several attempts, but the map keeps readjusting after a zoom in. The loop seems to be at least with the country filter, but possibly also with other filters.

**Comment by mjvanderveen** [comment]
Seems to work. Only functionality that is now lost is the zoom to the markers when you visit the dashboard page for the first time. With this change it shows the world map 3 times wide, without zoom in to the markers in the viewbox.

**Comment by mjvanderveen** [comment]
Zoom solved
