### ISSUE TITLE
Text

### ISSUE THREAD

**Issue by SvetlanaKalyagina** [rodekruis/shelter-database#22]
On the home page - below the video: ..."how t**E** create account"

**Comment by mjvanderveen** [comment]
@SvetlanaKalyagina I can't find this text, what exact page is it on?

**Comment by SvetlanaKalyagina** [comment]
Hm.. also cant find it anymore. I saw the video https://vimeo.com/209637494 somewhere on the homepage. The mistake in the text was below that video.

**Comment by mjvanderveen** [comment]
Unable to locate
