### ISSUE TITLE
Add shelter 2

### ISSUE THREAD

**Issue by SvetlanaKalyagina** [rodekruis/shelter-database#24]
1. When I create a new shelter there is no the Netherlands Red Cross in the list of organisations. I dont know, maybe it is not necessary)
2. When I choose the type of shelter, there are many times the same type in the list.

![shelter_types](https://cloud.githubusercontent.com/assets/25431703/25770936/23ef6376-3243-11e7-95ba-5377d75f8071.jpg)

**Comment by mjvanderveen** [comment]
This also happens on the development & staging environment. The fetchAssociatedDisasters function in src/web/static/js/contribute.js returns different results for the same type of disaster. It might be that this goes wrong at import of the data/shelters/Shelters_structure_small.csv (although this file contains the correct one entry). Another reason could be that the database is not cleaned correctly at import, however the database should be deleted and recreated (/create_db.sh and init_db.sh)

**Comment by mjvanderveen** [comment]
@thenav56 There seems to be only 3 options now under type of shelter when I rebuild the database with create.sh and init.sh. There should be more options

**Comment by thenav56** [comment]
@mjvanderveen The issue is fixed, now all are present. Please Verify if it meets your requirement.
